version: '2.1'

services:
  greeter_server:
    image: greeter_server
    build: ./greeter_server
    volumes:
      - './files:/go/src/app/files'
  greeter_client:
    image: greeter_client
    build: ./greeter_client
    links:
      - greeter_server
    ports:
      - 3030:3030
    environment:
      - "RPC_ADDRESS=greeter_server:5051"